command! Breakpoint call dap#breakpoints#toggle(v:null, v:null)
command! TestScratch call dap#repl#text_append_text()
command! TestRepl call dap#repl#create_new_buf()
command! Continue call dap#session#step_action("continue")
command! DapNext call dap#session#step_action("next")
command! DapStepIn call dap#session#step_action("stepIn")
command! StartDebugger call dap#init#start()
